### ISSUE TITLE
State of Unify 

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza-webapp-one#23]
Unify should be improved
 - improper mix of event handling, vuex, props...
 - multiple unneeded component loading
 - double layout -- one for desktop and one for mobile that replaces each other when screen width change and causes every tab/app to be opened twice, emmiting duplicated notifications, causing uneeded traffic ...
 - `v-if` conditions over entire template inside the component rather than on the component itself
 - unscoped styling that has too many responsibilities

Todo:
 - [ ] write down and rething all needed featues for Unify
 - [ ] design a proper app architecture that will support the features
 - [ ] see what can be salvaged from components, plugins, store
 - [ ] rewrite

**Comment by zmija** [comment]
Unrealistic for 2019.20, moving to 2020.03

**Comment by zmija** [comment]
On to-do for a year 🙈

**Comment by darh** [comment]
Finally.

**Comment by zmija** [comment]
awww yeah :D 👯
