### ISSUE TITLE
Unify layout settings saved per user

### ISSUE THREAD

**Issue by zmija** [cortezaproject/corteza-webapp-one#28]
As a user, I can adjust my Crust workspace with custom grid and custom set/order of open Crust tabs.

Current flow:
Currently, my settings are lost the moment I refresh the Unify page. It's also gone if I log out or when I log in to another device.

Expected flow:
As a user, I want to have the same layout available when I refresh the page or when I (re)login to the same or to the new device.

**Comment by zmija** [comment]
@darh assigning to you, for now, so you can add technical details. Feel free to re-assign to Tomaž or Jože.

**Comment by zmija** [comment]
We found out using the grid is not really popular among users, so I'm going to close this one for now.

**Comment by tawelton** [comment]
While I do agree that the grid is a somewhat unnecessary tool, I do think persisting the open set of tabs for a user across refreshes would be beneficial. Is this something that is already implemented? I cannot find any documentation to enable user state saving for the One app

**Comment by darh** [comment]
This was implemented in a recent (develop/unstable) version. But only stores layout & open tabs in a browser's local storage for now.

A couple things need to be implemented on the backend to allow per-user settings.
