### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by glittle** [cortezaproject/corteza-webapp-one#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Check browser console for errors.
![Screenshot_20190807-101237](https://user-images.githubusercontent.com/85186/62639058-fc420d00-b8fb-11e9-932e-a764b1024f9b.png)

**Desktop (please complete the following information):**
or copy-paste a link from https://www.whatsmybrowser.org/

**Smartphone (please complete the following information):**

**Additional context**

**Comment by darh** [comment]
Thank you @glittle. 
I hope I'll find time to fix this in next few days.

**Comment by darh** [comment]
Fixed.
