### ISSUE TITLE
Opening a new application in a tab opens the application in a new panel

### ISSUE THREAD

**Issue by lennyhorstink** [cortezaproject/corteza-webapp-one#36]
**Describe the bug**
Opening a new application in a tab opens the application in a new panel.

**To Reproduce**
1. Open https://latest.cortezaproject.org/
2. Click on [+] to open a new application
3. Click on "Low Code" -> "Open in Corteza One"
-> Now the screen looks like this:

![image](https://user-images.githubusercontent.com/34375645/66111630-8b506600-e5c9-11e9-95ee-2e61cd62c9f6.png)

**Expected behavior**
It should open in a tab, and a new panel should not appear

**Desktop (please complete the following information):**
Firefox, latest

**Comment by zmija** [comment]
@Fajfa as you probably noticed we now open 2 tabs by default - messaging and CRM (and not only messaging anymore). this change might be related to this bug.

**Comment by Fajfa** [comment]
Yup, very related. On it.

**Comment by Fajfa** [comment]
Fixed in https://github.com/cortezaproject/corteza-webapp-one/commit/d08a90f605b778bd688b3a5e6922f76cbb2aaf0a

**Comment by darh** [comment]
deployed to latest corteza & crust.
