### ISSUE TITLE
New layout > styling corrections

### ISSUE THREAD

**Issue by zmija** [cortezaproject/corteza-webapp-one#43]
- [ ] Add some margin to the bottom of the app selector

- [ ] Linux > double scrollbar in messaging
![image](https://user-images.githubusercontent.com/8327569/81052036-13318200-8ec3-11ea-8280-9e7d766d7817.png)

- [ ] perhaps the middle vertical line separating panels should be darker and not in the same tone as one of the app colours
![image](https://user-images.githubusercontent.com/8327569/81050992-3f4c0380-8ec1-11ea-8248-b3410d5f54b5.png)

- ~First tab position could be better parked to the left of the screen~

![Screen Shot 2020-05-05 at 11 02 22](https://user-images.githubusercontent.com/8327569/81050459-4e7e8180-8ec0-11ea-9081-b71ecbdac000.png)

**Comment by darh** [comment]
> First tab position could be better parked to the left of the screen

let's leave this one as it is. 
it's a bit off because of "tab scroller" that appears when tabs do not fit the available width
