### ISSUE TITLE
confirmation email was slow. question about crust/corteza

### ISSUE THREAD

**Issue by j2l** [cortezaproject/corteza-webapp-one#71]
Hello!

**Describe the bug**
I can't register at the community instance https://latest.cortezaproject.org

**To Reproduce**
https://latest.cortezaproject.org
create account
wait for confirmation email

**Expected behavior**
Get the confirmation email :smile: 

**Additional**
I didn't find a comparison page between crust github project and corteza. I see that crust is archived but is it the same features?
I'm looking for a low code platform for CRM but also be able to build simple PWA apps easily.
Thank you and have a great day!
:smile_cat:

**Comment by j2l** [comment]
BTW, by mistake when changing url, I found all namespaces on demo: https://latest.cortezaproject.org/compose/namespaces

**Comment by lennyhorstink** [comment]
Hi @j2l,

Thanks for informing us. I did a test and I can confirm that it takes long for the confirmation email to arrive. 5 minutes in my case. We'll look what we can do to improve this on the community server.

And to answer your additional question: indeed Crust is archived. All development is done in Corteza. So, I would suggest you use Corteza for your CRM and other apps.

**Comment by j2l** [comment]
Thanks @lenny-horstink !
All features are the same in the archived crust project and corteza?

**Comment by lennyhorstink** [comment]
Corteza has all the features from the archived Crust project, and a lot more :)

**Comment by j2l** [comment]
Ah, great! Thanks!
